In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.24.2


In [3]:
my_list = [1, 2, 3]

In [4]:
my_list

[1, 2, 3]

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
np.zeros((8, 15))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0, 11, 2)

array([ 0., 11.])

In [17]:
np.linspace(0,11, 5)

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [18]:
np.linspace(0, 11, 200)

array([ 0.        ,  0.05527638,  0.11055276,  0.16582915,  0.22110553,
        0.27638191,  0.33165829,  0.38693467,  0.44221106,  0.49748744,
        0.55276382,  0.6080402 ,  0.66331658,  0.71859296,  0.77386935,
        0.82914573,  0.88442211,  0.93969849,  0.99497487,  1.05025126,
        1.10552764,  1.16080402,  1.2160804 ,  1.27135678,  1.32663317,
        1.38190955,  1.43718593,  1.49246231,  1.54773869,  1.60301508,
        1.65829146,  1.71356784,  1.76884422,  1.8241206 ,  1.87939698,
        1.93467337,  1.98994975,  2.04522613,  2.10050251,  2.15577889,
        2.21105528,  2.26633166,  2.32160804,  2.37688442,  2.4321608 ,
        2.48743719,  2.54271357,  2.59798995,  2.65326633,  2.70854271,
        2.7638191 ,  2.81909548,  2.87437186,  2.92964824,  2.98492462,
        3.04020101,  3.09547739,  3.15075377,  3.20603015,  3.26130653,
        3.31658291,  3.3718593 ,  3.42713568,  3.48241206,  3.53768844,
        3.59296482,  3.64824121,  3.70351759,  3.75879397,  3.81

In [19]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.87680381, 0.140919  , 0.82950247, 0.88759795, 0.61177902])

In [22]:
np.random.rand(5, 5)

array([[0.46109229, 0.89396815, 0.42505158, 0.34720208, 0.1275196 ],
       [0.03024857, 0.23887993, 0.44970261, 0.43715582, 0.02213622],
       [0.29951499, 0.28695116, 0.14426108, 0.81968266, 0.1533731 ],
       [0.21412694, 0.3142755 , 0.1270518 , 0.36359396, 0.58707071],
       [0.73272311, 0.7286707 , 0.8828582 , 0.51330238, 0.93945583]])

In [23]:
np.random.randn(2)

array([0.37491654, 0.28887797])

In [24]:
np.random.randn(4,4)

array([[-0.77348145, -1.04804155,  1.15211738,  0.54790005],
       [-0.55266248, -0.42614914,  0.03935917, -0.04646572],
       [ 0.45537108,  0.01856705, -0.04276626,  0.27842584],
       [-1.12987197, -0.04247848, -1.79971178, -0.6517228 ]])

In [25]:
np.random.randint(2, 12)

4

In [26]:
np.random.randint(1, 100, 10)

array([50, 97, 66, 70, 86, 18, 31, 68, 70,  9])

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0, 50, 10)

In [30]:
ranarr

array([43,  8, 20, 27, 32, 18, 38, 13,  9, 44])

In [31]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr.reshape(5, 50)

ValueError: cannot reshape array of size 25 into shape (5,50)

In [33]:
ranarr

array([43,  8, 20, 27, 32, 18, 38, 13,  9, 44])

In [34]:
ranarr.max()

44

In [35]:
ranarr.min()

8

In [36]:
ranarr.argmax()

9

In [37]:
ranarr.argmin()

1

In [38]:
ranarr.shape

(10,)

In [39]:
arr.shape

(25,)

In [40]:
arr = arr.reshape(5, 5)

In [41]:
arr.shape

(5, 5)

In [42]:
arr.dtype

dtype('int64')

In [43]:
arr = np.arange(0, 11)

In [44]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[4]

4

In [46]:
arr[1:5]

array([1, 2, 3, 4])

In [47]:
arr[:5] = 100

In [48]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [49]:
arr = np.arange(0, 11)

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
slice_of_arr = arr[0:6]

In [52]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [53]:
slice_of_arr[:] = 99

In [54]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [55]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [56]:
arr_copy = arr.copy()

In [57]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [58]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [59]:
arr_copy[:] = 100

In [60]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [61]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [62]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [63]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [64]:
arr_2d[0][0]

5

In [65]:
arr_2d[0]

array([ 5, 10, 15])

In [66]:
arr_2d[0, 0]

5

In [67]:
arr_2d[1, 2]

30

In [68]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [69]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [70]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [71]:
arr_2d[1:, :2]

array([[20, 25],
       [35, 40]])

In [72]:
arr = np.arange(1, 11)

In [73]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
bool_arr = arr > 5

In [75]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [76]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [77]:
arr[arr < 5]

array([1, 2, 3, 4])

In [78]:
arr_2d = np.arange(50).reshape(5, 10)

In [79]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [80]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [81]:
arr_2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])